version: "3"

networks:
  blue_network:
    external: true

services:
  blue_nginx:
    image: nginx
    privileged: true
    networks:
      - default
      - blue_network
    ports:
      - "81:80"
    links:
      - blue_php
      - blue_mysql
      - blue_redis
    volumes:
      - ./back:/app
      - ./env/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./env/nginx/logs:/var/log/nginx/

  blue_php:
    build: ./env/php7.2
    privileged: true
    networks:
      - default
      - blue_network
    working_dir: /app
    expose:
      - 9000
    ports:
      - "9001:9001"
    volumes:
      - ./back:/app

  blue_mysql:
    image: mysql:5
    networks:
      - default
      - blue_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blue
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./env/mysql/data:/var/lib/mysql

  blue_redis:
    image: redis
    networks:
      - default
      - blue_network
    ports:
      - "6380:6379"

  blue_vue:
    build: ./env/vue
    privileged: true
    links:
      - blue_php
    networks:
      - default
      - blue_network
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app